# Generated by Django 5.0.1 on 2024-01-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.AddField(
            model_name='users',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
